version: '3.1'

services:
  mysql:
    container_name: mysql
    image: mysql:9.1.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  redis:
    container_name: redis
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "16379:6379"
