services:
  mysql:
    image: mysql:9.7.2
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '13306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./script/mysql:/docker-entrypoint-initdb.d:ro
  redis:
    image: redis:8.10.1
    container_name: redis
    restart: unless-stopped
    ports:
      - '16379:6379'
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
